#!/bin/sh
install_yay() {
    cd 
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    rm -rf yay
}
install_packages() {
    cd "$HOME/auto-rice"
    yay -Syu
    for package in $(cat packages)
    do
        yay -S  --noconfirm --needed "$packages"
    done
}
install_nvidia() {
	cd
	git clone https://aur.archlinux.org/nvidia-390xx.git
	cd nvidia-390xx
	makepkg -si
	rm -rf nvidia-390xx
}	
get_dotfiles() {
    cd
    git clone https://gitlab.com/mr-kat/dot-files
    cd dot-files/dwm-6.2
    make clean install
    rm -f config.h
}
echo Installing yay
install_yay
echo Installing other packages
install_packages
echo Installing nvidia
install_nvidia
echo Getting dotfiles
get_dotfiles

